### ISSUE TITLE
Looking for a beginner's guide

### ISSUE THREAD

**Issue by colingoldberg** [cu-clear/verbnet#16]
Hi,

As one who is fairly new to NLP, I have looked for, but have been unable to find a beginner's guide to VerbNet and its associated initiatives. Does anything like this exist? Even as I see that a lot (most?) of the Verbnet work was done in earlier years, I am encouraged that there is current work in evidence in this github repo. I would very much appreciate help in getting at least a basic understanding.

Can you help me?

Colin Goldberg

**Comment by Adamits** [comment]
Hi Colin,

You can see a representation of the current state of the project at the UVI website: https://verbs.colorado.edu/verb-index/vn3.3/ which is a good visual of the XML's in https://github.com/kevincstowe/verbnet/tree/master/verbnet3.3

Check out a VerbNet class, e.g. https://verbs.colorado.edu/verb-index/vn3.3/vn/run-51.3.2.php, which is a cluster of similar verbs. One of the current maintainers may also be able to point you to any up-to-date papers or documents.

**Comment by kevincstowe** [comment]
It might be useful to start at the ["How to Use Verbnet" page](https://verbs.colorado.edu/verbnet/). There's also some perhaps useful content in "Using VerbNet" and "Publications". If anything's still unclear, please feel free to contact me at kevin.stowe@colorado.edu. We're still doing a lot of work on VerbNet and would be happy to help out!

**Comment by colingoldberg** [comment]
Thanks, Kevin - I somehow missed the menu tabs on this page (I did come across some broken links on other pages).

Colin Goldberg


On February 7, 2019 at 6:13:18 PM, Kevin Stowe (notifications@github.com) wrote:

It might be useful to start at the "How to Use Verbnet" page. There's also some perhaps useful content in "Using VerbNet" and "Publications". If anything's still unclear, please feel free to contact me at kevin.stowe@colorado.edu. We're still doing a lot of work on VerbNet and would be happy to help out!

**Comment by colingoldberg** [comment]
Thanks for the quick response. And as pointed out in an email from Kevin Stowe, there is explanation at https://verbs.colorado.edu/verbnet/.

**Comment by colingoldberg** [comment]
Hi Kevin,

As I start looking into VerbNet, I have a few questions:

- I would like to know what progress has been made since the (average) date of the documentation that I see (forgive me if I have missed something) - ie. Some years ago.
- According to the home page (https://verbs.colorado.edu/verb-index/vn3.3/index.php), the total number of verbs is 9344. This is a much lower number that what I see, for example in the SUMO WordNetMappings30-verb.txt file - approx 13800 verbs (see https://github.com/ontologyportal/sumo/tree/master/WordNetMappings). Is there a resource in which I will be able to find more VerbNet verbs/classes? If not, are there plans to expand this number? Could you help me understand the ’state of the art’?

Thanks very much for your help - I do appreciate it.

Regards

Colin Goldberg


On February 7, 2019 at 6:13:18 PM, Kevin Stowe (notifications@github.com) wrote:

It might be useful to start at the "How to Use Verbnet" page. There's also some perhaps useful content in "Using VerbNet" and "Publications". If anything's still unclear, please feel free to contact me at kevin.stowe@colorado.edu. We're still doing a lot of work on VerbNet and would be happy to help out!

**Comment by kevincstowe** [comment]
What is the documentation that you're looking at? We are constantly working on updating and improving the resource, but of course the releases are less frequent. The most current version if 3.3, for which the XML files are available through this repository. It can also be browsed at http://verbs.colorado.edu/verb-index/vn3.3/.  All of the verbs found in VerbNet will be located in the XML and in this resource. We are always aiming to improve coverage, but please note we likely won't include all the entries in WordNet, as they include phrasal structures like "act_involuntarily" and "go_to_bed" that won't be added to VerbNet.

Our last few months of work has been aimed at updating the semantic predicates in the classes to incorporate other resources and technical updates to the UVI, both of which will be available soon, so we haven't added many verbs since 3.3.

**Comment by colingoldberg** [comment]
I think I might have been looking at pages such as http://verbs.colorado.edu/~mpalmer/projects/verbnet.html, which are different than your vn3.3 pages.

Thanks for this great resource. I do believe it is very important to expand coverage. I know this is a huge task, but it makes this resource even more valuable. I do wonder if the additional verbs in SUMO WordNetMappings could not be helpful in expanding VerbNet coverage - just a thought.
