### ISSUE TITLE
Names for new classes/types

### ISSUE THREAD

**Issue by colingoldberg** [cu-clear/verbnet#17]
Hi,

In the VerbNet_Guidelines.pdf document, the VerbNet Hierarchy table (page 6) shows column "Verb Type", going up to class 109. Do you have Verb Types (names) for the newer classes?

I also notice that reciprocate-112 and respond-113 are included in the newer classes. But it seems there is a possibility that these belong under Communication (class 37). Can you clarify?

Thanks

Colin Goldberg

**Comment by kevincstowe** [comment]
We don't have general verb types for the newer classes, but they can be found in the hierarchy page of the UVI:
http://verbs.colorado.edu/verb-index/vn3.3/vn/class-h.php

VerbNet classes are based on syntactic and semantic behavior. Reciprocate-112 and respond-112 indicate a reaction to something, and thus have a predicate "in_reaction_to". They also have specific syntactic structures that the verbs can employ. Note that respond-112 can only take prepositional arguments. The thematic roles and syntactic and semantic frames comprise the nature of the class, and verbs that exhibit different behavior with regard to these structures are split into these separate classes. I hope that's helpful!

**Comment by colingoldberg** [comment]
This is helpful, although my first thought on seeing respond-112 was that it does belong to Communication. On second thought about reciprocate-113, I would place it in Act if it was my decision.

I also find it noticeable that classes beyond 57 are (mostly) just one per Type.

I am trying to get a grip on the Class Types (eg. Communication) to see where I can place them in my "model". They are almost like instances of "Process" in the SUMO upper ontology. 

Just FYI, I am in the process of building a graph database from this data (using Neo4j).

**Comment by kevincstowe** [comment]
Ah, yes! That makes sense. I think the issue is that we don't formally use these Verb Types for anything - they were based on Levin's book, but we don't treat them as part of VerbNet's structure. As we added the classes after about 60, they mostly just get their own "Type". I think something we need to look into is reorganizing all of these classes into appropriate verb types-I'll look into it!
