### ISSUE TITLE
Hierarchy for New Thematic Roles

### ISSUE THREAD

**Issue by sshearman** [cu-clear/verbnet#19]
Over the last few releases some new thematic roles have been added

In the VerbNet Guidelines it shows the thematic role hierarchy - but doesnt include these new roles.

How do these fit into the hierarchy?

Initial_State
Axis
Precondition
Reflexive
Context
Affector

**Comment by kevincstowe** [comment]
Thanks for the note! We're looking into it now, and I'll get back to you with a new updated thematic role hierarchy!
