### ISSUE TITLE
Comparing Semantics

### ISSUE THREAD

**Issue by kevincstowe** [cu-clear/verbnet#3]
Write a fancy 'contains' method that tells whether semantic frame contains predicates
Used to check if a frame contains the necessary predicates to match a new GL semantics - if it does, we can replace it automatically. If not, we have to look at it further.

```
class SemanticFrame:
  def contains([predicate nodes]/SemanticFrame object):
    ..
  if type(input) == list:
    then its predicate nodes and check for all of them
  elif type(input) == SemanticFrame:
    iterate through it's predicate nodes and check all of them!
   return True/False
```

**Comment by Adamits** [comment]
Would you expect that this method cares if predicate.contains(arguments from preds in the input), or only that it contains the values of the input predicates (e.g. "path_rel"). 

When we spoke, I was thinking that we had a use case for passing a small subset of arguments that the predicate must have, but now I am second guessing whether that is the purpose of this method or not.

**Comment by kevincstowe** [comment]
I would think there will be some cases where the argments to the predicates are important as well.
