### ISSUE TITLE
uvi.colorado.edu has stopped working properly

### ISSUE THREAD

**Issue by sshearman** [cu-clear/verbnet#33]
The online version uvi.colorado.edu has stopped working properly

1/ It seems a recent update to the UVI has stopped some features working.
When I go into a verb - and click on propbank - i can only display details of first roleset
When I click on the 2nd or 3rd role set it doesnt respond

2/ Also sometimes I the higher level menu to see framenet/propbank/ontonotes doesnt respond

3/ The contact us form returns an error!
(hence why I am posting here)

This is a very useful tool as a quick reference - please fix - and keep up the good work.

**Comment by akhileshappala** [comment]
Apologies for the late response. 

The verbnet update has been fixed long back.
The "contact us" page has been fixed recently. we will be receiving the emails if you want to contact us for any of the details.

Even you can post here, From now on we will be actively taking care of the issues.
