### ISSUE TITLE
Error when loading VerbNet 3.4 (but not 3.2 or 3.3) using verbnet.py

### ISSUE THREAD

**Issue by aaronstevenwhite** [cu-clear/verbnet#36]
I receive the following error when attempting to load VerbNet 3.4 using `verbnet.VerbNetParser(version="3.4")`.

```
    328         """Get all the thematic roles for a verb class ans their selectional
    329         restrictions."""
--> 330         return [ThematicRole(them_soup, self.version) for them_soup in self.soup.THEMROLES.find_all("THEMROLE")]
    331 
    332     def _subclass(self):

AttributeError: 'NoneType' object has no attribute 'find_all'
```

Analogous errors do *not* arise when attempting to load v3.2 and v3.3 using `verbnet.VerbNetParser(version="3.2")` and `verbnet.VerbNetParser(version="3.3")`, respectively.

**Comment by ghamzak** [comment]
Solved. Try it now please!

**Comment by aaronstevenwhite** [comment]
Confirming that it now works. Thank you!
